Accept a canvas as parameter as well
buunguyen/exif-orient pull request #3
Opened 2016-10-19 09:43 UTC by Prinzhorn

I use https://github.com/nodeca/pica to resize huge images and want to rotate the result of the orientation. Accepting a canvas as parameter as well makes sense and the changes are simple enough.

I also changed the demo as I was confused why it didn't reflect my changes while I was trying them and found that it links to the version on GH.

2016-10-19 17:56 UTC, buunguyen requested changes

2016-10-19 17:56 UTC, buunguyen commented on exif-orient.js
> +    if (typeof img !== 'string' && !(img instanceof HTMLImageElement || img instanceof HTMLCanvasElement)) {
Easier to read if not mixing & and |:
```js
if (typeof img !== 'string' && !(img instanceof HTMLImageElement) && !(img instanceof HTMLCanvasElement))
```

2016-10-19 17:56 UTC, buunguyen commented on exif-orient.js
>     * @return {HTMLCanvasElement} a canvas object.
Need to update comment, currently {HTMLImageElement | String}

2016-10-19 17:56 UTC, buunguyen commented on demo/index.html
> +  <script src="../exif-orient.js"></script>
Have you tested that this change work when accessed via http://rawgit.com/YOUR-NAME/exif-orient/master/demo/index.html?

2016-10-20 09:28 UTC, Prinzhorn commented on demo/index.html
> +  <script src="../exif-orient.js"></script>
See http://rawgit.com/prinzhorn/exif-orient/accept-canvas/demo/index.html

2016-10-20 09:32 UTC, Prinzhorn commented
I updated the if statement and the comment

2016-10-22 04:28 UTC, merged